[package]
name = "main-ui"
version = "0.7.4"
authors.workspace = true
description.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
reqwest.workspace = true
dto.workspace = true
dioxus = { workspace = true, features = ["router"] }

dioxus-aws = { version = "0.6.15" }
dioxus-web = { workspace = true, optional = true }
dioxus-logger = { version = "0.5.0" }
tracing = { version = "0.1.40" }

wasm-bindgen = { version = "0.2.100", optional = true }
wasm-bindgen-futures = { version = "0.4.50", optional = true }
web-sys = { version = "0.3.72", features=["Navigator", "HtmlCollection"], optional = true}
serde = "1.0.216"
num-format = "0.4.4"

dioxus-sdk = { workspace = true, optional = true }

dioxus-popup.workspace = true
dioxus-translate.workspace = true
dioxus-oauth = { workspace = true }

chrono = "0.4.39"
base64 = "0.22.1"
url = "2.5.4"
rest-api.workspace = true
by-macros.workspace = true
by-types.workspace = true
by-components.workspace = true
jsonwebtoken = "9.3.0"

[features]
default = []
web = ["web-only", "dioxus-aws/web"]
web-only = ["web-sys", "wasm-bindgen", "wasm-bindgen-futures", "dioxus-aws/web-only", "dioxus-web", "dioxus-sdk", "dioxus-oauth/web", "dioxus-translate/web", "by-components/web", "rest-api/web"]
server = ["dioxus-aws/server"]
lambda = ["server", "dioxus-aws/lambda"]
