[package]
name = "main-api"
version = "0.7.4"
authors.workspace = true
description.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
dto = { workspace = true, features = [ "server" ] }
serde.workspace = true
serde_json.workspace = true
slog.workspace = true
by-axum.workspace = true
easy-dynamodb.workspace = true

tokio = { version = "1.40.0", features = ["full"] }
tower = "0.5.1"
chrono = "0.4.39"
reqwest.workspace = true
uuid = { version = "1.10.1", features = ["v4"] }
rest-api.workspace = true
by-types.workspace = true
sqlx.workspace = true
tracing = { version = "0.1.41" }
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
validator = "0.20.0"

[features]
default = []
lambda = ["by-axum/lambda"]
